### ISSUE TITLE
no handling for change-deleted hook

### ISSUE THREAD

**Issue by jf-ct** [nlsdfnbch/gerrit-hooks#10]
https://gerrit.googlesource.com/plugins/hooks/+/refs/heads/stable-2.15/src/main/resources/Documentation/hooks.md#change_deleted

```
Traceback (most recent call last):
  File "...", line ..., in <module>
    gerrit_parser = gerrit_hooks.build_parser_for(args.gerrit_event)
  File "/usr/local/lib/python3.5/dist-packages/gerrit_hooks/hook.py", line 37, in build_parser_for
    cli_flags = HookFlagDefinitions()[hook_type]
  File "/usr/local/lib/python3.5/dist-packages/gerrit_hooks/containers.py", line 172, in __getitem__
    flag_string = self.__mapping__[item]
KeyError: 'change-deleted'
```

**Comment by deepbrook** [comment]
Should be fixed in the latest release!
